stages:
- build

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script: "mvn clean package"
  artifacts:
    name: "Skyblock"
    paths:
    - "/builds/Songoda/Skyblock/target/*.jar"
#    - "/builds/Songoda/EpicAnchors/Read_this_before_your_first_use.txt"
