image: gradle:alpine

variables:
  name: "FabledSkyBlock"
  path: "/builds/$CI_PROJECT_PATH"
  version: "2.0.7"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script:
    - find $path/ -type f -name "*.gradle" -print0 | xargs -0 sed -i -e s/maven-version-number/$version/g
    - gradle build
    - mv $path/build/libs/*.jar $path/
  artifacts:
    paths:
      - $path/*.jar
