Settings:
    Visitor:
        Destroy: false
        Place: false
        Anvil: false
        ArmorStand: false
        Beacon: false
        Bed: false
        AnimalBreeding: false
        Brewing: false
        Bucket: false
        WaterCollection: false
        Storage: false
        Workbench: false
        Crop: false
        Door: false
        Gate: false
        Projectile: false
        Enchant: false
        Fire: false
        Furnace: false
        HorseInventory: false
        MobRiding: false
        MobHurting: false
        MobTaming: true
        Leash: false
        LeverButton: false
        Milking: false
        Jukebox: false
        PressurePlate: false
        Redstone: false
        Shearing: false
        Trading: false
        ItemDrop: false
        ItemPickup: false
        Fishing: false
        DropperDispenser: false
        SpawnEgg: false
        Cake: false
        DragonEggUse: false
        MinecartBoat: false
        Portal: false
        Hopper: false
    Member:
        Destroy: true
        Place: true
        Anvil: true
        ArmorStand: true
        Beacon: true
        Bed: true
        AnimalBreeding: true
        Brewing: true
        Bucket: true
        WaterCollection: true
        Storage: true
        Workbench: true
        Crop: true
        Door: true
        Gate: true
        Projectile: true
        Enchant: true
        Fire: true
        Furnace: true
        HorseInventory: true
        MobRiding: true
        MobHurting: true
        MobTaming: true
        Leash: true
        LeverButton: true
        Milking: true
        Jukebox: true
        PressurePlate: true
        Redstone: true
        Shearing: true
        Trading: true
        ItemDrop: true
        ItemPickup: true
        Fishing: true
        DropperDispenser: true
        SpawnEgg: true
        MinecartBoat: true
        Cake: true
        DragonEggUse: true
        Portal: true
        Hopper: true
    Operator:
        Invite: true
        Kick: true
        Ban: true
        Unban: true
        Visitor: true
        Member: true
        Island: false
        MainSpawn: false
        VisitorSpawn: true
        Biome: true
        Weather: true
    Owner:
        NaturalMobSpawning: true
        MobGriefing: false
        PvP: false
        Explosions: false
        FireSpread: true
        LeafDecay: true
        KeepItemsOnDeath: true